@echo off
REM **************************************************************************
REM
REM  Installation batch file for Telix for DOS v3.5x Shareware version
REM
REM  Do not remove or modify this file in any way. Otherwise problems
REM  may occur during the installation process or later with Telix itself.
REM
REM  Copyright (c) 1996 deltaComm Development, Inc.
REM
REM **************************************************************************
INST.EXE
MODEMCFG.EXE
cls
